# -*- coding: utf-8 -*-
"""RandomVariables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdYt-Q5kic_vXY7W_sTeB07O3GEuDvUT
"""

import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(page_title="MIND: Making Inference Digestible", layout="centered")

st.title("🧠 MIND: Making Inference Digestible")
st.subheader("🎯 Interactive Probability & Statistics Explorer")

st.markdown("""
Welcome to MIND, an interactive app designed to help you understand **discrete probability distributions**.
Enter values for a random variable and corresponding probabilities, and visualize the distribution live.
""")

# Collect input
x_input = st.text_input("Enter values for random variable X (comma-separated):", "0, 1, 2, 3")
p_input = st.text_input("Enter corresponding probabilities P(X) (fractions or decimals, comma-separated):", "0.1, 0.3, 0.4, 0.2")

try:
    x_vals = [float(x.strip()) for x in x_input.split(',')]
    p_vals = [eval(p.strip()) for p in p_input.split(',')]  # Supports fractions
    assert np.isclose(sum(p_vals), 1), "Probabilities must sum to 1."

    df = pd.DataFrame({'X': x_vals, 'P(X)': p_vals})
    df['Cumulative P(X)'] = df['P(X)'].cumsum()
    st.dataframe(df)

    st.bar_chart(df.set_index("X")["P(X)"])

    st.success("✅ Valid distribution!")
except Exception as e:
    st.error(f"❌ Error: {e}")